import { siteConfig } from "@/lib/site-config";

// Keep the visible notice and its Markdown representation in sync.
export const privacySections = [
  { title: "Who to contact", text: `This notice describes personal information handled through the Neex Creative website. For questions about your information, contact ${siteConfig.email} or ${siteConfig.phone}. Our contact address is ${siteConfig.address.street}, ${siteConfig.address.city}, ${siteConfig.address.postalCode}, Ireland.` },
  { title: "Project enquiries", text: "The quote form asks for your name, email, service and message, with optional phone, location and project details. These details allow us to respond to your request and discuss the work you want to commission. Please avoid sending passwords, payment details or sensitive personal information. Depending on the form configuration, submitting either sends your details through a form delivery service or opens your email application with a draft that you must send yourself." },
  { title: "Website and external services", text: "This website includes Google Ads measurement code and an embedded Google map. These services may receive technical information such as your IP address, browser details and page activity, and may use cookies. Booking links open Calendly; WhatsApp, social media and portfolio links open the named external services. Those providers handle information under their own privacy notices. Your browser settings can restrict cookies, although some features may then behave differently." },
  { title: "Questions and your rights", text: `Email ${siteConfig.email} to ask what personal information is held about you, how it is used, which providers receive it, or how long it is retained. You may request access, correction or deletion and, where applicable, restriction, objection or portability. These rights depend on the circumstances and applicable law. You can also raise a concern with Ireland's Data Protection Commission at https://www.dataprotection.ie/.` },
];
